name: lucky

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Build
        run: |
          cd shell
          bash lucky.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lucky
          path: shell/lucky/bin/*.zip
